# Generated by Django 4.0.5 on 2022-06-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boleto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boleto',
            unique_together={('usuario', 'partido')},
        ),
    ]
