# Generated by Django 4.0.5 on 2022-06-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_boleto_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boleto',
            unique_together=set(),
        ),
    ]
