# Generated by Django 4.0.5 on 2022-06-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_boleto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(default='x', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partido',
            name='estadio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.CharField(max_length=100),
        ),
    ]
