# Generated by Django 4.0.5 on 2022-06-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_partido_grupo_alter_partido_estadio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='grupo',
            field=models.CharField(max_length=100),
        ),
    ]
