# Generated by Django 4.0.5 on 2022-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='fecha_compra',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
