# Generated by Django 4.0.5 on 2022-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_boleto_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
