# Generated by Django 4.0.5 on 2022-06-08 15:54

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_boleto_fecha_compra"),
    ]

    operations = [UnaccentExtension(), TrigramExtension()]
